version: "3.4"

services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq_server
    ports:
      - "5672:5672"      # Broker port
      - "15672:15672"    # Management UI
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    networks:
      - combined-network

  publisher:
    build: ./publisher
    container_name: fastapi_publisher
    depends_on:
      - rabbitmq
    environment:
      - BROKER_URL=amqp://guest:guest@rabbitmq:5672/
    ports:
      - "8000:8000"
    networks:
      - combined-network

  worker:
    build: ./worker
    container_name: faststream_worker
    depends_on:
      - rabbitmq
    environment:
      - BROKER_URL=amqp://guest:guest@rabbitmq:5672/
    networks:
      - combined-network

networks:
  combined-network:
    driver: bridge